version: '3.4'

x-common-variables: &common-variables
 MYSQL_HOST: mysql
 MYSQL_ROOT_PASSWORD: mysql123
 MYSQL_USER: mysql
 MYSQL_PASSWORD: mysql123
 MYSQL_DATABASE: hse-api-database
 HSELING_RPC_ENDPOINT: http://localhost:5000/rpc
 HSELING_API_ENDPOINT: http://localhost:5000/api
 RESTRICTED_MODE: 0

services:
 hse-api-web:
  build:
    context: .
    dockerfile: hseling-api-generator/Dockerfile
  ports:
   - "5000:80"
  depends_on:
    - mysql
  environment: *common-variables
  volumes:
    - type: bind
      source: ./hseling_data_generator
      target: /data

 hse-web-web:
  build: ./hseling-web-generator
  ports:
    - "8000:80"
  depends_on:
    - hse-api-web
  environment: *common-variables
  volumes:
    - type: bind
      source: ./hseling_data_generator
      target: /data

 mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment: *common-variables
